name: Deploy Glue script (dev)

on:
  push:
    branches:
      - main
    paths:
      - glue/**
  workflow_dispatch:

env:
  AWS_REGION: eu-central-1
  SCRIPT: requestsAggregation.py

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${AWS_REGION}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: upload to S3
        run: aws s3 cp ./${SCRIPT} s3://${{ secrets.S3_BUCKET }}
        working-directory: glue
